=== marianafranco/compilador-fm/trunk/CompiladorFM/conf/automato.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT gramatica (estado+)>
<!ELEMENT estado (id,final,tipo,(transicao)* )>
<!ELEMENT id (#PCDATA)*>
<!ELEMENT final (#PCDATA)*>
<!ELEMENT tipo (#PCDATA)*>
<!ELEMENT transicao (entradas, proximo)>
<!ELEMENT entradas (#PCDATA)*>
<!ELEMENT proximo (#PCDATA)*>

=== marianafranco/compilador-fm/p2/conf/metalexico.xml
<!DOCTYPE gramatica SYSTEM "automato.dtd">
<gramatica>
	<estado>
		<id>0</id>
		<final>false</final>
		<tipo>0</tipo>
		<transicao>
			<entradas>"</entradas>
			<proximo>1</proximo>
		</transicao>
		<transicao>
			<entradas>(){}[]=|.</entradas>
			<proximo>3</proximo>
		</transicao>
		<transicao>
			<entradas>abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_</entradas>
			<proximo>4</proximo>
		</transicao>
	</estado>
	<estado>
		<id>1</id>
		<final>false</final>
		<tipo>0</tipo>
		<transicao>
			<entradas>abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789</entradas>
			<proximo>5</proximo>
		</transicao>
		<transicao>
			<entradas>!@#$%*()_+-={}[];.,/?\|&lt;&gt;&amp;_</entradas>
			<proximo>5</proximo>
		</transicao>
		<transicao>
			<entradas>"`</entradas>
			<proximo>5</proximo>
		</transicao>
	</estado>
	<estado>
		<id>5</id>
		<final>false</final>
		<tipo>0</tipo>
		<transicao>
			<entradas>abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789</entradas>
			<proximo>5</proximo>
		</transicao>
		<transicao>
			<entradas>!@#$%*()_+-={}[];.,/?\|&lt;&gt;&amp;</entradas>
			<proximo>5</proximo>
		</transicao>
		<transicao>
			<entradas>"</entradas>
			<proximo>2</proximo>
		</transicao>
	</estado>
	<estado>
		<id>2</id>
		<final>true</final>
		<tipo>1</tipo>
	</estado>
	<estado>
		<id>3</id>
		<final>true</final>
		<tipo>2</tipo>
	</estado>
	<estado>
		<id>4</id>
		<final>true</final>
		<tipo>3</tipo>
		<transicao>
			<entradas>abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_</entradas>
			<proximo>4</proximo>
		</transicao>
	</estado>
</gramatica>

=== marianafranco/compilador-fm/p2/conf/automato.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE gramatica SYSTEM "automato.dtd">
<gramatica>
    <estado>
		<id>0</id>
		<final>false</final>
        <tipo>0</tipo>
		<transicao>
			<entradas>ISK()</entradas>
			<proximo>1</proximo>
		</transicao>
    </estado><estado>
		<id>1</id>
		<final>true</final>
        <tipo>1</tipo>
	</estado>
</gramatica>
