=== marianafranco/compilador-fm/p2/conf/metacompilador.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT gramatica (nterminal+)>
<!ELEMENT nterminal (nome,(estado)+)>
<!ELEMENT nome (#PCDATA)*>
<!ELEMENT estado (id,final,(transicao)* )>
<!ELEMENT id (#PCDATA)*>
<!ELEMENT final (#PCDATA)*>
<!ELEMENT transicao (entradas, proximo)>
<!ELEMENT entradas (#PCDATA)*>
<!ELEMENT proximo (#PCDATA)*>

=== marianafranco/compilador-fm/trunk/CompiladorFM/metacompilador.xml
<!DOCTYPE gramatica SYSTEM "metacompilador.dtd">
<gramatica>
	<nterminal>
		<nome>WIRTH</nome>
		<estado>
			<id>0</id>
			<final>false</final>
			<transicao>
				<entradas>NTERM</entradas>
				<proximo>2</proximo>
			</transicao>
		</estado>
		<estado>
			<id>2</id>
			<final>false</final>
			<transicao>
				<entradas>"="</entradas>
				<proximo>3</proximo>
			</transicao>
		</estado>
		<estado>
			<id>3</id>
			<final>false</final>
			<transicao>
				<entradas>EXPR</entradas>
				<proximo>4</proximo>
			</transicao>
		</estado>
		<estado>
			<id>4</id>
			<final>false</final>
			<transicao>
				<entradas>"."</entradas>
				<proximo>1</proximo>
			</transicao>
		</estado>
		<estado>
			<id>1</id>
			<final>true</final>
			<transicao>
				<entradas>NTERM</entradas>
				<proximo>2</proximo>
			</transicao>
		</estado>
	</nterminal>
	<nterminal>
		<nome>EXPR</nome>
		<estado>
			<id>0</id>
			<final>false</final>
			<transicao>
				<entradas>TERM</entradas>
				<proximo>1</proximo>
			</transicao>
			<transicao>
				<entradas>NTERM</entradas>
				<proximo>1</proximo>
			</transicao>
			<transicao>
				<entradas>"e"</entradas>
				<proximo>1</proximo>
			</transicao>
			<transicao>
				<entradas>"("</entradas>
				<proximo>2</proximo>
			</transicao>
			<transicao>
				<entradas>"{"</entradas>
				<proximo>4</proximo>
			</transicao>
			<transicao>
				<entradas>"["</entradas>
				<proximo>6</proximo>
			</transicao>
		</estado>
		<estado>
			<id>2</id>
			<final>false</final>
			<transicao>
				<entradas>EXPR</entradas>
				<proximo>3</proximo>
			</transicao>
		</estado>
		<estado>
			<id>3</id>
			<final>false</final>
			<transicao>
				<entradas>")"</entradas>
				<proximo>1</proximo>
			</transicao>
		</estado>
		<estado>
			<id>4</id>
			<final>false</final>
			<transicao>
				<entradas>EXPR</entradas>
				<proximo>5</proximo>
			</transicao>
		</estado>
		<estado>
			<id>5</id>
			<final>false</final>
			<transicao>
				<entradas>"}"</entradas>
				<proximo>1</proximo>
			</transicao>
		</estado>
		<estado>
			<id>6</id>
			<final>false</final>
			<transicao>
				<entradas>EXPR</entradas>
				<proximo>7</proximo>
			</transicao>
		</estado>
		<estado>
			<id>7</id>
			<final>false</final>
			<transicao>
				<entradas>"]"</entradas>
				<proximo>1</proximo>
			</transicao>
		</estado>
		<estado>
			<id>1</id>
			<final>true</final>
			<transicao>
				<entradas>"|"</entradas>
				<proximo>8</proximo>
			</transicao>
		</estado>
		<estado>
			<id>8</id>
			<final>false</final>
			<transicao>
				<entradas>TERM</entradas>
				<proximo>1</proximo>
			</transicao>
			<transicao>
				<entradas>NTERM</entradas>
				<proximo>1</proximo>
			</transicao>
			<transicao>
				<entradas>"e"</entradas>
				<proximo>1</proximo>
			</transicao>
			
			<transicao>
				<entradas>"("</entradas>
				<proximo>2</proximo>
			</transicao><transicao>
				<entradas>"{"</entradas>
				<proximo>4</proximo>
			</transicao>
			<transicao>
				<entradas>"["</entradas>
				<proximo>6</proximo>
			</transicao>
		</estado>
	</nterminal>
</gramatica>
